### ISSUE TITLE
Falta subir ramas

### ISSUE THREAD

**Issue by LigiaCano** [LigiaCano/SpaiEcp2LigiaCano#10]
No se subieron las ramas de la mejoras:
Feature#02
Feature#05
Feature#08
Tal vez falto configurar subir todas las ramas

**Comment by ghost** [comment]
Sí, perdona el despiste, se me olvidó hacer lo de "Add All Branches Spec". Ya están subidas las tres ramas.

Saludos.

**Comment by LigiaCano** [comment]
Listo gracias
